// Deterministic game-state smoke tests with a minimal DOM and Canvas stub.
// These are not a substitute for visual/browser QA.
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
function setup(saved=null){
 const nodes=new Map(),all=[],events={},timers=[],tools={};let raf;
 class Node{constructor(id=''){this.id=id;this.hidden=false;this.children=[];this.dataset={};this.style={};this.attrs={};this.textContent='';this._html='';this.classList={add(){},remove(){},toggle(){}};all.push(this)}set innerHTML(x){this._html=x;this.children=[]}get innerHTML(){return this._html}appendChild(x){this.children.push(x)}setAttribute(k,v){this.attrs[k]=v}addEventListener(k,f){this[k]=f}querySelector(s){return this.sub??(this.sub=new Node())}focus(){}closest(){return null}getContext(){return new Proxy({},{get:()=>()=>{}})}toDataURL(){return 'data:image/png;base64,'}getBoundingClientRect(){return {left:0,top:0,width:960,height:540}}}
 const get=s=>{if(s==='#choices button')return get('#choices').children[0]||null;if(!nodes.has(s))nodes.set(s,new Node(s));return nodes.get(s)};
 let store=saved?JSON.stringify(saved):null;
 const document={querySelector:get,querySelectorAll(s){if(s==='[data-place]')return all.filter(x=>x.dataset.place);if(s==='[data-dir]')return [];return []},createElement:()=>new Node(),addEventListener(){},modelContext:{registerTool:t=>tools[t.name]=t}};
 const sandbox={document,window:{addEventListener:(k,f)=>events[k]=f},localStorage:{getItem:()=>store,setItem:(k,v)=>store=v},matchMedia:()=>({matches:true}),setInterval:()=>1,clearInterval(){},setTimeout:(f)=>{timers.push(f);return 1},clearTimeout(){},requestAnimationFrame:f=>raf=f,AbortController,console,Math,JSON,Object,Array,String,Number,Set};
 vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/story.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/game.js'),'utf8'),sandbox);
 let time=0;function tick(){time+=40;raf(time)};function runTimers(){while(timers.length)timers.shift()()};function start(){get('#startBtn').onclick();runTimers()};function progress(){return tools.read_evening_breeze_progress.execute({})};
 function move(id){all.find(x=>x.dataset.place===id).onclick();for(let i=0;i<500&&!get('#dialogue').hidden===false;i++)tick();for(let i=0;i<500&&get('#dialogue').hidden;i++)tick();assert(!get('#dialogue').hidden,'dialogue starts '+id)}
 function advance(seed,letter,wrong=false){let count=0,w=false;while(!get('#dialogue').hidden&&count++<180){const ch=get('#choices').children;if(ch.length){let label;let text=get('#dialogueText').textContent;if(text.includes('第一步'))label=wrong&&!w?(w=true,'中火烘烤'):'小火预热';else if(text.includes('稳定的热'))label='中火烘烤';else if(text.includes('最后一步'))label='关火，等一会儿';else if(ch.some(b=>b.textContent.includes('金盏花')))label=seed==='mint'?'薄荷：给经过的人泡一杯茶':'金盏花：给阴天留一点颜色';else if(ch.some(b=>b.textContent==='明天的自己'))label={self:'明天的自己',traveler:'还在远处赶路的人',town:'这里的人们'}[letter];(ch.find(b=>b.textContent===label)||ch[0]).onclick()}else get('#nextBtn').onclick();}assert(count<180,'no dialogue loop');runTimers()}
 return {get,start,move,advance,progress,tool:tools.read_evening_breeze_progress,store:()=>JSON.parse(store),runTimers,events,tick};
}
for(const seed of ['flower','mint'])for(const letter of ['self','traveler','town']){const g=setup();g.start();for(const [i,id]of ['post','bakery','river','garden','post'].entries()){g.move(id);g.advance(seed,letter,i===1);assert.equal(g.progress().chapter,i+1)}assert.deepEqual(Array.from(g.progress().memories).length,3);assert(g.store().finished);assert.equal(g.store().seed,seed);assert.equal(g.store().letter,letter);assert(!g.get('#ending').hidden);assert(g.get('#endingLetter').textContent.includes(seed==='mint'?'薄荷':'金盏花'));const resumed=setup(g.store());assert(!resumed.get('#continueBtn').hidden);resumed.get('#continueBtn').onclick();assert(resumed.progress().finished);assert.throws(()=>resumed.tool.execute({invalid:true}),/Expected an empty object/);console.log('PASS',seed,letter,'full story, wrong oven recovery, save/continue')}
console.log('All six ending/seed combinations passed deterministic state tests.');
